### ISSUE TITLE
Krane config file

### ISSUE THREAD

**Issue by david-castaneda** [krane/krane#34]
Krane's startup configuration is entirely managed through environment variables.

```bash
export KRANE_PRIVATE_KEY=""
export DB_PATH=""
export LETSENCRYPT_EMAIL=""
```

 It would be very convenient to have such configurations persisted to a file, like a configuration file that gets picked up by Krane during startup. Environment variables can optionally be used to configure this file and the idea is environment variables would overwrite default values set in the configuration file.

`krane.yaml`

```yaml
---
krane:
  log_level: debug # Log level used by Krane specific logs
  ssh_keys: "usr/home/.ssh" # Path to the your ssh keys directory
  domain: "krane.example.com" # DNS domain used by Krane to receive requests
  https: true # Secure TLS communication (Powered by Lets Encrypt)
  db:
    path: "/tmp/krane.db" # Database path where Krane stores data
  workers: 1 # Workers parallelize executing jobs from the queue
  queue:
    size: 1 # Jobs queued at any given time 
    retry_policy: 1 # Amount of retries for a job for a failed job
proxy:
  enabled: true # If the DNS proxy (Traefik) should be running
  domain: "proxy.example.com" # DNS domain used by Traefik to receive requests
  https: true  # Secure TLS communication (Powered by Lets Encrypt)
  letsencrypt:
    email: "me@example.com"  # Email used to generate Lets Encrypt certificates
```

- Proposed configuration would be in YAML since it's a standard configuration format that allows the use of comments
- The configuration file allows you to configure the Krane and Proxy config
